spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/WebSocket?serverTimezone=UTC
    username: suhyuk0544
    password: suhyuk1027
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    hikari:
#      jdbc-url: jdbc:mysql://localhost:8080/Server?serverTimezone=UTC
#      username: suhyuk0544
#      password: suhyuk1027

#redis:
#  port: 6379
#  host: localhost

  jpa:
    hibernate:
      ddl-auto: create-drop

#    database-platform:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: suhyuk0544
      password: suhyuk1027
  cache:
    redis:
      time-to-live: 86400
  data:
    redis:
      host: localhost
      port: 6379

